name: Docker Image CI for Samba

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch: # Agrega esta entrada para habilitar la ejecución manual
    branches: [ "master", "main" ] # Opcional: restringe las ramas donde se puede ejecutar

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Download codigo from repo
      
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_HUB }}
        password: ${{ secrets.PASS_HUB }}
        
    
    - name: Build and push the Docker image latest
      run: |
        docker build . --file Dockerfile --tag neytor/samba && 
        docker image ls && docker push neytor/samba

    - name: Build and push the Docker image with tag
      run: |
        docker build . --file Dockerfile --tag neytor/samba:v4-19-6 && \
        docker image ls && docker push neytor/samba:v4-19-6
      
    

